"""Generate STATUS.md from a conformance + oracle + redteam run.

Usage (from proxy/):
    python3 tests/rfc0002/gen_status.py && cat tests/rfc0002/STATUS.md
"""
from __future__ import annotations

import subprocess
import sys
import defusedxml.ElementTree as ET
from pathlib import Path

OUT = Path(__file__).parent / "STATUS.md"
JUNIT_XML = Path(__file__).parent / "_status_junit.xml"

# Static wired-into-request-path state — updated as phases land.
# ponytail: grep-based auto-detection not worth it for 6 entries.
WIRED = {
    "§4.2 substrate (signed envelope)": True,
    "§5 content-class eval": False,
    "§6 federation / trust-scope": False,
    "§7 APE signing": False,
    "§7 C2PA assertion": False,
    "§7.1 claude-hook": False,
}


def run_tests() -> dict[str, str]:
    """Run conformance+oracle+redteam markers, return {test_nodeid: outcome}."""
    cmd = [
        sys.executable, "-m", "pytest",
        "tests/rfc0002",
        "-m", "conformance or oracle or redteam or substrate",
        f"--junit-xml={JUNIT_XML}",
        "-q", "--tb=no",
    ]
    subprocess.run(cmd, cwd=Path(__file__).parents[2], capture_output=True)  # noqa: S603

    if not JUNIT_XML.exists():
        return {}

    tree = ET.parse(JUNIT_XML)  # noqa: S314
    outcomes: dict[str, str] = {}
    for tc in tree.iter("testcase"):
        nodeid = f"{tc.get('classname', '')}.{tc.get('name', '')}"
        if tc.find("failure") is not None:
            outcomes[nodeid] = "fail"
        elif tc.find("error") is not None:
            outcomes[nodeid] = "fail"
        elif tc.find("skipped") is not None:
            skipped = tc.find("skipped")
            msg = skipped.get("message", "") if skipped is not None else ""
            outcomes[nodeid] = "xfail" if "xfail" in msg.lower() else "skip"
        else:
            outcomes[nodeid] = "pass"
    return outcomes


SECTIONS = [
    ("§4.2 substrate (signed envelope)", "oracle", ["test_substrate_rfc0001"]),
    ("§5 content-class eval", "conformance+parity", ["test_b1_", "test_registry_", "test_b1_union"]),
    ("§6 federation / trust-scope", "conformance+parity", ["test_b3_", "test_s5_"]),
    ("§7 APE signing", "conformance", ["test_s6_artifact"]),
    ("§7 C2PA assertion", "conformance", ["test_s6_c2pa"]),
    ("§7.1 claude-hook", "conformance", ["test_s7_"]),
]


def classify(outcomes: dict[str, str], prefixes: list[str]) -> str:
    matching = [v for k, v in outcomes.items() if any(p in k for p in prefixes)]
    if not matching:
        return "skip"
    if "fail" in matching:
        return "fail"
    if all(v == "xfail" for v in matching):
        return "xfail"
    if any(v == "xfail" for v in matching):
        return "xfail"
    return "pass"


def main() -> None:
    outcomes = run_tests()
    if JUNIT_XML.exists():
        JUNIT_XML.unlink()

    rows = []
    for section, marker_hint, prefixes in SECTIONS:
        parity = classify(outcomes, prefixes)
        wired = "yes" if WIRED.get(section) else "no"
        rows.append((section, marker_hint, parity, wired))

    lines = [
        "# RFC-0002 Implementation Status",
        "",
        "_Generated by `python3 tests/rfc0002/gen_status.py`. Do not edit by hand._",
        "",
        "| Section | Test coverage | Oracle/parity | Wired into request path |",
        "| ------- | ------------- | ------------- | ----------------------- |",
    ]
    for section, marker_hint, parity, wired in rows:
        lines.append(f"| {section} | `{marker_hint}` | {parity} | {wired} |")

    lines += [
        "",
        "## Key",
        "- **pass** — all tests in this section pass against `app.services.*`",
        "- **xfail** — known divergence tracked (N1/N2); will flip to xpass when fixed",
        "- **fail** — unexpected failure; investigate before merging",
        "- **skip** — feature not yet scaffolded",
        "",
        "## Notes",
        "- §4.2 substrate is the only section fully wired into the request path.",
        "- §5/§6/§7: services scaffolded, oracle-parity verified where applicable, **NOT enforced**.",
        "- D1 applied: oracle `system-*` renamed to `system/*` (spec §2 `<domain>/<subtype>` format).",
        "- D2 recorded: impl `PipelineStep` has single `integrity_rank`; oracle's own/input/tool",
        "  decomposition not representable. Closing D2 is a Phase-1 design item.",
    ]

    OUT.write_text("\n".join(lines) + "\n")
    print(OUT.read_text())


if __name__ == "__main__":
    main()
