"""
mcphub_sdk.scaffold — Project scaffolder for new SDK-based MCP servers.

Usage
-----
    python -m mcphub_sdk.scaffold <name> [--service-name NAME] [--port PORT]

Creates ./<name>/ containing:
  server.py            — Runnable SDK stub (identity from identity(), NOT tool params)
  Dockerfile           — FROM mcphub-sdk:base, COPY server.py
  requirements.txt     — Extra deps only (base image already has mcp/uvicorn/httpx/mcphub_sdk)
  compose-snippet.yaml — Paste-ready service block for podman-compose.lab.yml

Security note (H3 / FO-1)
--------------------------
The generated server.py NEVER shows user_sub / caller / principal as tool parameters.
Identity is ONLY resolved via identity() which reads the proxy-injected X-User-Sub header.
A tool parameter for identity is forgeable — the SDK + proxy are the enforcement point.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Template strings
# ---------------------------------------------------------------------------

_SERVER_PY = '''\
"""
{name} MCP Server — generated by `python -m mcphub_sdk.scaffold`.

SECURITY (H3 / FO-1): Identity MUST come from identity(), never a tool parameter.
  - Do NOT add user_sub / caller / principal / caller_id / principal_id as tool args.
  - Those are forgeable by the caller. The proxy injects X-User-Sub; identity() reads it.
"""
from mcphub_sdk import PlatformMCPServer, identity, credential

# Set credential_env only if your tools call an authenticated backend service.
# Example: credential_env="{service_name_upper}_TOKEN"
srv = PlatformMCPServer("{name}-mcp")


@srv.tool()
async def example(query: str) -> dict:
    """Replace with your tool logic.

    Identity comes EXCLUSIVELY from identity() — the proxy-injected X-User-Sub header.
    NEVER add user_sub / caller / principal as a tool parameter (forgeable).
    """
    who = identity()                          # who.sub / who.role (from X-User-Sub)
    # Uncomment if your tool calls an authenticated backend:
    # token = credential(env_var="{service_name_upper}_TOKEN")  # injected Authorization, env fallback (proxied only)
    return {{"echo": query, "caller": who.sub}}


if __name__ == "__main__":
    srv.run()  # HOST / PORT from env; defaults 0.0.0.0:8000
'''

_DOCKERFILE = '''\
# Requires the SDK base image: run `make sdk-base` first.
# The base image (mcphub-sdk:base) already contains:
#   python:3.12-slim (non-root appuser:appgroup), mcp, uvicorn, httpx, mcphub_sdk
FROM mcphub-sdk:base
COPY --chown=appuser:appgroup server.py .
CMD ["python", "server.py"]
'''

_REQUIREMENTS_TXT = '''\
# The mcphub-sdk:base image already provides:
#   mcp>=1.8.0  uvicorn>=0.30.0  httpx>=0.27.0  mcphub_sdk
#
# List only EXTRA dependencies your server adds below.
# Example:
#   redis[hiredis]>=5.0.0
#   httpx>=0.27.0   # already in base — only list if you need a newer pin
'''

# ---------------------------------------------------------------------------
# Compose snippet — mirrors the real lab-mcp-echo block exactly.
#
# Healthcheck test string is copied verbatim from podman-compose.lab.yml
# (lab-mcp-echo block, line ~485).  It POSTs an MCP `initialize` to /mcp
# and exits 0 if the response contains b'serverInfo'.
#
# H1 (from spec): the scaffold MUST use the /mcp initialize POST pattern,
# NOT a /health probe (even though the SDK also serves /health).
# This matches the proven lab pattern and what the proxy health-gates on.
# ---------------------------------------------------------------------------

_HEALTHCHECK_TEST = (
    r"""["CMD-SHELL", "python3 -c \"import urllib.request,json,sys; r=urllib.request.urlopen(urllib.request.Request('http://localhost:8000/mcp',data=json.dumps({'jsonrpc':'2.0','method':'initialize','id':1,'params':{'protocolVersion':'2024-11-05','capabilities':{},'clientInfo':{'name':'hc','version':'1'}}}).encode(),headers={'Content-Type':'application/json','Accept':'application/json, text/event-stream'},method='POST')); sys.exit(0 if b'serverInfo' in r.read() else 1)\" 2>/dev/null"]"""
)

_COMPOSE_SNIPPET = '''\
# ── {name} MCP — paste this block into podman-compose.lab.yml ─────────────────
#
# TODO: choose a free host port (currently {port}) and confirm it does not
#       conflict with other services.
#
# TODO: add the pairwise network definition under the top-level `networks:` key:
#
#   networks:
#     mcp-{name}-net:
#       internal: true
#
# Also add  mcp-{name}-net  to the proxy's `networks:` list so it can reach
# this server.
#
# Build order: `make sdk-base` FIRST (builds mcphub-sdk:base), then
#   podman-compose -f podman-compose.lab.yml build lab-mcp-{name}
# ---------------------------------------------------------------------------
  lab-mcp-{name}:
    <<: *mcp-hardening
    build:
      context: ./lab/mcp-servers/{name}
    image: lab-mcp-{name}:lab
    container_name: lab-mcp-{name}
    ports:
      - "127.0.0.1:{port}:8000"
    environment:
      HOST: "0.0.0.0"
      PORT: "8000"
      SERVER_NAME: "{name}-mcp"
      FASTMCP_TRANSPORT_SECURITY__ENABLE_DNS_REBINDING_PROTECTION: "false"
      # TODO: add service-specific env vars here (e.g. API tokens, URLs).
      # Secrets: inject via .env or a secrets manager — never hardcode.
    networks:
      - lab-net
      - mcp-{name}-net   # pairwise net with proxy only; replaces internal-net
    healthcheck:
      # H1: uses the MCP initialize POST to /mcp — do NOT replace with /health.
      # Copied verbatim from the lab-mcp-echo block in podman-compose.lab.yml.
      test: {healthcheck_test}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
'''

_NEXT_STEPS = """\
Generated {count} files in {out_path}/

Next steps:
  1.  If you haven't already:  make sdk-base
        (builds mcphub-sdk:base — required before building any SDK server)

  2.  Copy {out_path}/ to ./lab/mcp-servers/{name}/
        (or adjust the `build.context` in compose-snippet.yaml accordingly)

  3.  Paste compose-snippet.yaml into podman-compose.lab.yml
      and add the pairwise network definition (see TODO comments in the snippet).

  4.  Build and start the lab:
        podman-compose -f podman-compose.lab.yml build lab-mcp-{name}
        make lab-up

  5.  Onboard the server (register tools + injection mode):
        python scripts/onboard_server.py \\
            --url http://lab-mcp-{name}:8000 \\
            --mode <header|env|vault> \\
            [--token-env {service_name_upper}_TOKEN]
"""


# ---------------------------------------------------------------------------
# Public API (importable + testable)
# ---------------------------------------------------------------------------


def scaffold(
    name: str,
    *,
    out_dir: str | Path = ".",
    service_name: str | None = None,
    port: int = 8000,
) -> Path:
    """Generate a new SDK-based MCP server directory.

    Parameters
    ----------
    name:
        Server slug used for directory name, container name, service name, and
        the FastMCP server name (e.g. ``"my-service"`` → dir ``my-service/``,
        server name ``"my-service-mcp"``).
    out_dir:
        Parent directory to create ``<name>/`` inside.  Defaults to ``"."``.
    service_name:
        Optional human-readable service label used in comments.  Defaults to
        the uppercased, hyphen-stripped form of ``name`` (e.g.
        ``"my-service"`` → ``"MY_SERVICE"``).
    port:
        Host port to bind in the compose snippet (``127.0.0.1:<port>:8000``).
        Defaults to ``8000``.  The TODO comment reminds the operator to pick a
        free port.

    Returns
    -------
    Path
        Absolute path to the newly created ``<name>/`` directory.
    """
    svc = service_name or name.upper().replace("-", "_")
    out_path = Path(out_dir).resolve() / name
    out_path.mkdir(parents=True, exist_ok=False)

    files: dict[str, str] = {
        "server.py": _SERVER_PY.format(name=name, service_name_upper=svc),
        "Dockerfile": _DOCKERFILE,
        "requirements.txt": _REQUIREMENTS_TXT,
        "compose-snippet.yaml": _COMPOSE_SNIPPET.format(
            name=name,
            port=port,
            healthcheck_test=_HEALTHCHECK_TEST,
        ),
    }

    for filename, content in files.items():
        (out_path / filename).write_text(content, encoding="utf-8")

    print(
        _NEXT_STEPS.format(
            count=len(files),
            out_path=out_path,
            name=name,
            service_name_upper=svc,
        )
    )

    return out_path


# ---------------------------------------------------------------------------
# CLI entry point  (python -m mcphub_sdk.scaffold)
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        prog="python -m mcphub_sdk.scaffold",
        description=(
            "Scaffold a new SDK-based MCP server.\n\n"
            "Creates ./<name>/ with server.py, Dockerfile, requirements.txt, "
            "and a compose-snippet.yaml to paste into podman-compose.lab.yml."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("name", help="Server slug (e.g. 'my-service')")
    parser.add_argument(
        "--service-name",
        dest="service_name",
        default=None,
        help="Human-readable service label used in comments (default: NAME uppercased).",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8000,
        help="Host port to use in the compose snippet (default: 8000).",
    )
    parser.add_argument(
        "--out-dir",
        dest="out_dir",
        default=".",
        help="Parent directory for the new server dir (default: current directory).",
    )
    args = parser.parse_args(argv)

    try:
        scaffold(
            args.name,
            out_dir=args.out_dir,
            service_name=args.service_name,
            port=args.port,
        )
    except FileExistsError:
        print(
            f"error: directory '{args.name}' already exists in '{args.out_dir}'. "
            "Remove it or choose a different name.",
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
