#!/usr/bin/env bash
# lab-init.sh — CB-006 / 6.7: generate fresh lab secrets and write .env.lab
#
# Creates .env.lab with randomly generated secrets for all lab services.
# Safe to re-run: if .env.lab already exists it exits 0 without overwriting
# (use --force to regenerate).
#
# WARNING — --force on a running lab:
#   DB_PASSWORD, REDIS_PASSWORD, MINIO_ROOT_PASSWORD, VAULT_TOKEN are
#   stored inside data volumes. Rotating them with --force while the lab
#   is running will break the services. Do one of:
#     a) make lab-down (without --volumes) + edit .env.lab manually
#     b) make lab-down --volumes (destroys all data) + lab-init-force + lab-up
#
# Usage:
#   scripts/lab-init.sh             # create .env.lab if absent
#   scripts/lab-init.sh --force     # overwrite existing .env.lab
#   make lab-init                   # same as above (no --force)
#   make lab-init-force             # same as --force
#
# Generated file is listed in .gitignore — never commit it.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_LAB="${REPO_ROOT}/.env.lab"
FORCE=false
if [[ "${1:-}" == "--force" ]]; then
  FORCE=true
fi

if [[ -f "${ENV_LAB}" && "${FORCE}" == "false" ]]; then
  echo "INFO: ${ENV_LAB} already exists — skipping generation."
  echo "      Use 'scripts/lab-init.sh --force' or 'make lab-init-force' to regenerate."
  echo "      WARNING: --force on a running lab will break DB/Redis/MinIO/Vault."
  exit 0
fi

rand32() { openssl rand -hex 32; }
randpass() { openssl rand -base64 24 | tr -d '/+=' | head -c 28; }

echo "Generating lab secrets → ${ENV_LAB} ..."

# Generated once and reused below: the mcp-proxy Keycloak client secret must be
# IDENTICAL in KC_PROXY_CLIENT_SECRET (realm import) and OIDC_CLIENT_SECRET (the
# value the proxy presents to KC's token endpoint in oidc_browser.py). If they
# differ — or OIDC_CLIENT_SECRET is unset — KC returns 401 → token_exchange_failed.
KC_PROXY_SECRET="$(rand32)"

cat > "${ENV_LAB}" << ENVEOF
# .env.lab — generated by scripts/lab-init.sh
# DO NOT COMMIT. Listed in .gitignore.
# Regenerate (destroys volumes first): make lab-down-volumes && make lab-init-force && make lab-up

# ── Proxy signing / HMAC keys (required — no default in config.py) ────────────
PROXY_SECRET_KEY=$(rand32)
API_KEY_HMAC_KEY=$(rand32)
SBOM_SIGNING_KEY=$(rand32)
AUDIT_LOG_HMAC_KEY=$(rand32)
WEBHOOK_SIGNING_KEY=$(rand32)

# ── Core data-store passwords (CAUTION: changing these on a running lab
#    requires manual password reset in each service or a volume wipe) ──────────
DB_PASSWORD=$(rand32)
REDIS_PASSWORD=$(rand32)
MINIO_ROOT_USER=mcp-minio-admin
MINIO_ROOT_PASSWORD=$(rand32)
VAULT_TOKEN=$(rand32)

# ── Keycloak admin + OIDC client secrets ──────────────────────────────────────
KC_ADMIN_PASSWORD=$(randpass)
KC_PROXY_CLIENT_SECRET=${KC_PROXY_SECRET}
KC_GRAFANA_CLIENT_SECRET=$(rand32)

# ── Lab user passwords (imported into Keycloak realm on first start) ──────────
DEX_ALICE_PASSWORD=$(randpass)
DEX_BOB_PASSWORD=$(randpass)

# ── Grafana admin ─────────────────────────────────────────────────────────────
LAB_GRAFANA_ADMIN_PASSWORD=$(randpass)

# ── NetBox services ───────────────────────────────────────────────────────────
LAB_NETBOX_DB_PASSWORD=$(randpass)
LAB_NETBOX_REDIS_PASSWORD=$(randpass)
LAB_NETBOX_ADMIN_PASSWORD=$(randpass)
LAB_NETBOX_SECRET_KEY=$(rand32)

# ── Gitea admin ───────────────────────────────────────────────────────────────
GITEA_ADMIN_USER=gitadmin
GITEA_ADMIN_PASSWORD=$(randpass)
GITEA_ADMIN_EMAIL=admin@lab.local

# ── Gateway shared secret (nginx → proxy mTLS bypass) ─────────────────────────
GATEWAY_SHARED_SECRET=$(rand32)

# ── OIDC callback host config (Option B — derive from request Host header) ────
OIDC_TRUST_FORWARDED_HOST=true
PROXY_BASE_URL=
# PROXY_ALLOWED_HOSTS: comma-separated allow-list for Host header validation.
# Add your LAN/Tailscale IPs here (e.g. localhost:8000,203.0.113.10:8000).
# Leave empty to skip the check (any host accepted — safe on trusted LAN/VPN).
PROXY_ALLOWED_HOSTS=

# ── Keycloak OIDC config (wired to lab-keycloak on port 8082) ─────────────────
OIDC_ENABLED=true
OIDC_ISSUER_URL=http://localhost:8082/realms/mcp
OIDC_INTERNAL_ISSUER_URL=http://lab-keycloak:8080/realms/mcp
OIDC_CLIENT_ID=mcp-proxy
# Must equal KC_PROXY_CLIENT_SECRET (mcp-proxy KC client secret); see note above.
OIDC_CLIENT_SECRET=${KC_PROXY_SECRET}
OIDC_AUDIENCE=mcp-proxy

# ── Tailscale / LAN access ────────────────────────────────────────────────────
# Set LAB_HOST to your machine's LAN or Tailscale IP so Keycloak OIDC
# redirect URIs are correct when accessing from that address.
LAB_HOST=localhost

# ── External service tokens (fill in if using real integrations) ───────────────
GRAFANA_URL=http://lab-grafana:3000
GRAFANA_SERVICE_ACCOUNT_TOKEN=
NETBOX_URL=http://lab-netbox:8080
NETBOX_TOKEN=
GITEA_ADMIN_TOKEN=

# ── Azure / M365 (leave empty unless you have an Entra app registration) ──────
AZURE_TENANT_ID=
AZURE_CLIENT_ID=
AZURE_CLIENT_SECRET=
M365_USER=
REQUIRE_DELEGATED=
NATIVE_AUTH=
M365_RESOURCE_URL=
ENVEOF

chmod 600 "${ENV_LAB}"
echo "OK: ${ENV_LAB} written (mode 600)."
echo ""
echo "Next steps:"
echo "  1. Edit .env.lab: set LAB_HOST to your LAN/Tailscale IP."
echo "  2. Full fresh start: make lab-down-volumes && make lab-up"
echo "     OR to preserve existing data:"
echo "       make lab-down && make lab-up"
echo "       then reset DB password manually:"
echo "         DB_PASS=\$(grep ^DB_PASSWORD= .env.lab | cut -d= -f2)"
echo "         podman exec mcp-db psql -U mcp_app -d mcp_security -c \"ALTER USER mcp_app PASSWORD '\${DB_PASS}';\""
