#!/usr/bin/env bash
# lab-init.sh — CB-006 / 6.7: generate fresh lab secrets and write .env.lab
#
# Creates .env.lab with randomly generated secrets for all lab services.
# Safe to re-run: if .env.lab already exists it exits 0 without overwriting
# (use --force to regenerate).
#
# Usage:
#   scripts/lab-init.sh            # create .env.lab if absent
#   scripts/lab-init.sh --force    # overwrite existing .env.lab
#   make lab-init                  # same as above (no --force)
#
# Generated file is listed in .gitignore — never commit it.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_LAB="${REPO_ROOT}/.env.lab"
FORCE=false
if [[ "${1:-}" == "--force" ]]; then
  FORCE=true
fi

if [[ -f "${ENV_LAB}" && "${FORCE}" == "false" ]]; then
  echo "INFO: ${ENV_LAB} already exists — skipping generation."
  echo "      Use 'scripts/lab-init.sh --force' or 'make lab-init-force' to regenerate."
  exit 0
fi

rand32() {
  openssl rand -hex 32
}

rand16() {
  openssl rand -hex 16
}

# Passwords should be printable but avoid shell-special chars ($, `, \, ").
# Use base64 (URL-safe subset) for passwords used in shell strings.
randpass() {
  openssl rand -base64 24 | tr -d '/+=' | head -c 28
}

echo "Generating lab secrets → ${ENV_LAB} ..."

cat > "${ENV_LAB}" <<EOF
# .env.lab — generated by scripts/lab-init.sh
# DO NOT COMMIT. Listed in .gitignore.
# Regenerate: make lab-init-force

# ── Keycloak admin + OIDC client secrets ──────────────────────────────────────
KC_ADMIN_PASSWORD=$(randpass)
KC_PROXY_CLIENT_SECRET=$(rand32)
KC_GRAFANA_CLIENT_SECRET=$(rand32)

# ── Lab user passwords (imported into Keycloak realm) ─────────────────────────
DEX_ALICE_PASSWORD=$(randpass)
DEX_BOB_PASSWORD=$(randpass)

# ── Grafana admin ─────────────────────────────────────────────────────────────
LAB_GRAFANA_ADMIN_PASSWORD=$(randpass)

# ── NetBox services ───────────────────────────────────────────────────────────
LAB_NETBOX_DB_PASSWORD=$(randpass)
LAB_NETBOX_REDIS_PASSWORD=$(randpass)
LAB_NETBOX_ADMIN_PASSWORD=$(randpass)
LAB_NETBOX_SECRET_KEY=$(rand32)

# ── Gitea admin ───────────────────────────────────────────────────────────────
GITEA_ADMIN_USER=gitadmin
GITEA_ADMIN_PASSWORD=$(randpass)
GITEA_ADMIN_EMAIL=admin@lab.local

# ── Core proxy secrets (override .env values for lab) ─────────────────────────
# These match the required fields in proxy/app/core/config.py.
DB_PASSWORD=$(rand32)
REDIS_PASSWORD=$(rand32)

# ── Vault dev-mode token (lab only) ──────────────────────────────────────────
VAULT_TOKEN=$(rand32)

# ── Gateway shared secret (nginx → proxy mTLS bypass) ─────────────────────────
GATEWAY_SHARED_SECRET=$(rand32)

# ── OIDC callback host config (Option B — derive from request Host header) ────
OIDC_TRUST_FORWARDED_HOST=true
PROXY_BASE_URL=

# ── Keycloak OIDC config (wired to lab-keycloak on port 8082) ─────────────────
OIDC_ENABLED=true
OIDC_ISSUER_URL=http://\${LAB_HOST:-localhost}:8082/realms/mcp
OIDC_INTERNAL_ISSUER_URL=http://lab-keycloak:8080/realms/mcp
OIDC_CLIENT_ID=mcp-proxy
OIDC_AUDIENCE=mcp-proxy

# ── External service tokens (fill in if using real integrations) ───────────────
GRAFANA_URL=http://lab-grafana:3000
GRAFANA_SERVICE_ACCOUNT_TOKEN=
NETBOX_URL=http://lab-netbox:8080
NETBOX_TOKEN=
GITEA_ADMIN_TOKEN=

# ── Tailscale / LAN access (fill in your Tailscale IP if needed) ──────────────
LAB_HOST=localhost

# ── Azure / M365 (leave empty unless you have an Entra app registration) ──────
AZURE_TENANT_ID=
AZURE_CLIENT_ID=
AZURE_CLIENT_SECRET=
M365_USER=
REQUIRE_DELEGATED=
NATIVE_AUTH=
M365_RESOURCE_URL=
EOF

chmod 600 "${ENV_LAB}"
echo "OK: ${ENV_LAB} written (mode 600)."
echo ""
echo "Next steps:"
echo "  1. Edit .env.lab and set LAB_HOST to your LAN/Tailscale IP if needed."
echo "  2. Restart lab: make lab-down && make lab-up"
echo "     (Keycloak re-imports realm with new passwords on first start only.)"
