-- V056__server_sbom_cyclonedx.sql
-- PRD-0005 R-5 step 2: store a full CycloneDX SBOM generated by syft at scan
-- time, so the security analyst can download a standard SBOM for a submission
-- (richer than the declared-dependency inventory in sbom_components, which stays
-- as the always-available fallback). Generation is SOFT-FAIL: a syft failure or
-- absent binary leaves this NULL and never blocks or fails the scan.

ALTER TABLE server_registry
    ADD COLUMN IF NOT EXISTS sbom_cyclonedx JSONB;

COMMENT ON COLUMN server_registry.sbom_cyclonedx IS
    'PRD-0005 R-5: syft-generated CycloneDX SBOM captured at submission scan time (soft-fail, analyst context only, never a gate).';
